version: "3.7"
services:
  app:
    build:
      context: .
    environment:
      SHELL: /bin/zsh
    command: |
      sh -c 'while sleep 3600; do :; done'
    volumes:
      - app:/app
      - home:/home/app
      - ..:/original:cached
      - ~/.gitconfig:/home/app/.gitconfig:ro
      - ~/.zshrc:/home/app/.zshrc:ro
      - ~/.netrc:/home/app/.netrc:ro
volumes:
  app:
  home:
